#!/bin/bash

# GID/UIDs for Munge and Slurm users must be the same on every node; verify that these are available or change as necessary 
export MUNGEGID=500 
export MUNGEUID=500
export SLURMGID=501
export SLURMUID=501

export DEST=/admin   # The location of the directory to build Slurm RPMs
export VER=17.11.7

# Create global user accounts on all of the nodes in the cluster. These must be created identically on all of the nodes and
# done prior to installing the RPMs
sudo groupadd -g $MUNGEGID munge
sudo useradd -u $MUNGEUID -m -c "MUNGE authentication service" -d /var/lib/munge -g munge  -s /sbin/nologin munge
MUNGEUSER=$(id -u munge)

sudo groupadd -g $SLURMGID slurm
sudo useradd -u $SLURMUID -m -c "Slurm workload manager" -d /var/lib/slurm  -g slurm  -s /bin/bash slurm
SLURMUSER=$(id -u slurm)

# In case Slurm already exists but with the wrong ids:
sudo usermod -o -u $SLURMUSER slurm
sudo groupmod -o -g $SLURMUSER slurm

# Install epel-release on all of the nodes
sudo yum install -y epel-release

# Install MUNGE on all of the nodes 
sudo yum install -y munge munge-libs munge-devel

# Set the permissions for MUNGE directories on all of the nodes
sudo chown -R munge: /etc/munge/ /var/log/munge/
sudo chmod 0700 /etc/munge/ /var/log/munge/

# Install the dependencies for Slurm
sudo yum install -y rpm-build gcc openssl openssl-devel libssh2-devel pam-devel numactl numactl-devel 
sudo yum install	-y hwloc hwloc-devel lua lua-devel readline-devel rrdtool-devel ncurses-devel gtk2-devel man2html 
sudo yum install	-y libibmad libibumad perl-Switch perl-ExtUtils-MakeMaker
sudo yum install -y mariadb-server mariadb-devel

# Download the Slurm 17.11.7 tarball
mv files/slurm-$VER.tar.bz2 $DEST
cd $DEST
#wget https://download.schedmd.com/slurm/slurm-17.11.7.tar.bz2

# Build the RPMs
sudo rpmbuild -ta slurm-$VER.tar.bz2

# Install the RPMs on all of the nodes; RPMs on each node can vary by configuration, but
# this is my starting point
cd $DEST/rpmbuild/RPMS/x86_64
export VER=17.11.7-1

sudo yum install -y slurm-$VER.el7.x86_64.rpm
sudo yum install -y slurm-perlapi-$VER.el7.x86_64.rpm
sudo yum install -y slurm-openlava-$VER.el7.x86_64.rpm
sudo yum install -y slurm-contribs-$VER.el7.x86_64.rpm
sudo yum install -y slurm-devel-$VER.el7.x86_64.rpm
sudo yum install -y slurm-example-configs-$VER.el7.x86_64.rpm
sudo yum install -y slurm-libpmi-$VER.el7.x86_64.rpm
sudo yum install -y slurm-pam_slurm-$VER.el7.x86_64.rpm
sudo yum install -y slurm-slurmctld-$VER.el7.x86_64.rpm
sudo yum install -y slurm-slurmd-$VER.el7.x86_64.rpm
sudo yum install -y slurm-torque-$VER.el7.x86_64.rpm 

# Create the files and directories for use by Slurm that are not created during install; set the 
# permissions for the files and directories
sudo mkdir /var/spool/slurmctld /var/log/slurm
sudo chown slurm: /var/spool/slurmctld /var/log/slurm
sudo chmod 755 /var/spool/slurmctld /var/log/slurm

sudo touch /var/log/slurm/slurmctld.log
sudo chown slurm: /var/log/slurm/slurmctld.log

sudo touch /var/log/slurm/slurm_jobacct.log /var/log/slurm/slurm_jobcomp.log
sudo chown slurm: /var/log/slurm/slurm_jobacct.log /var/log/slurm/slurm_jobcomp.log

sudo mkdir /var/spool/slurm
sudo chown slurm: /var/spool/slurm

sudo mkdir /var/spool/slurmd
sudo chown slurm: /var/spool/slurmd  /var/log/slurm
sudo chmod 755 /var/spool/slurmd  /var/log/slurm

sudo touch /var/log/slurm/slurmd.log
sudo chown slurm: /var/log/slurm/slurmd.log

sudo chown slurm: /etc/slurm

sudo touch /etc/slurm/cgroup.conf
